const router = require('express').Router()

const auth = require('~/routes/auth')
const user = require('~/routes/user')
const email = require('~/routes/email')
const adminInvitation = require('~/routes/adminInvitation')
const question = require('~/routes/question')
const resourcesCategory = require('~/routes/resourcesCategory')
const category = require('~/routes/category')
const offer = require('~/routes/offer')
const googleAuth = require('~/routes/googleAuth')
const subject = require('~/routes/subject')
const location = require('~/routes/location')

router.use('/auth', auth)
router.use('/auth/google-auth', googleAuth)
router.use('/location', location)
router.use('/users', user)
router.use('/send-email', email)
router.use('/admin-invitations', adminInvitation)
router.use('/questions', question)
router.use('/resources-categories', resourcesCategory)
router.use('/categories', category)
router.use('/offers', offer)
router.use('/subjects', subject)

module.exports = router
